//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int Id { get; set; }
        public int IdTratamiento { get; set; }
        public string Nombre { get; set; }
        public string UrlJuego { get; set; }
        public string Descripcion { get; set; }
        public string Tarea { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string Velocidad { get; set; }
        public string Dificultad { get; set; }
        public Nullable<decimal> Tiempo { get; set; }
    }
}
