//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        public int Id { get; set; }
        public int IdTratamiento { get; set; }
        public int IdActividad { get; set; }
        public int IdUsuario { get; set; }
        public int Aciertos { get; set; }
        public int Errores { get; set; }
        public string Autoevaluacion { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    }
}
