//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        public int Id { get; set; }
        public int IdTratamiento { get; set; }
        public int IdActividad { get; set; }
        public int IdUsuario { get; set; }
        public int Aciertos { get; set; }
        public int Errores { get; set; }
        public string Autoevaluacion { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    }
}
