//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VResultado
    {
        public string TRATAMIENTO { get; set; }
        public string ACTIVIDAD { get; set; }
        public string PACIENTE { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string SEXO { get; set; }
        public int ACIERTOS { get; set; }
        public int ERRORES { get; set; }
    }
}
