//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VResultado
    {
        public string TRATAMIENTO { get; set; }
        public string ACTIVIDAD { get; set; }
        public string VELOCIDAD { get; set; }
        public string DIFICULTAD { get; set; }
        public Nullable<decimal> TIEMPO { get; set; }
        public string PACIENTE { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string SEXO { get; set; }
        public int ACIERTOS { get; set; }
        public int ERRORES { get; set; }
    }
}
